// Code generated by "stringer -type=PathElementKind"; DO NOT EDIT.

package curve

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MoveToKind-1]
	_ = x[LineToKind-2]
	_ = x[QuadToKind-3]
	_ = x[CubicToKind-4]
	_ = x[ClosePathKind-5]
}

const _PathElementKind_name = "MoveToKindLineToKindQuadToKindCubicToKindClosePathKind"

var _PathElementKind_index = [...]uint8{0, 10, 20, 30, 41, 54}

func (i PathElementKind) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_PathElementKind_index)-1 {
		return "PathElementKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PathElementKind_name[_PathElementKind_index[idx]:_PathElementKind_index[idx+1]]
}
